image: gitpod/workspace-full

tasks:
  - name: Run Django
    init: |
      pip install -r requirements.txt
      python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000

ports:
  - port: 8000
    onOpen: open-preview
