# Generated by Django 5.0 on 2025-04-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ingredients')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meals')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orders')),
            ],
            options={
                'db_table': 'meal_customizations',
            },
        ),
        migrations.DeleteModel(
            name='MealIngredients',
        ),
    ]
