# Generated by Django 5.0 on 2025-04-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mealcustomization_delete_mealingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredients')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meals')),
            ],
            options={
                'db_table': 'meal_ingredients',
                'unique_together': {('meal', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='meals',
            name='ingredients',
            field=models.ManyToManyField(through='core.MealIngredient', to='core.ingredients'),
        ),
    ]
