# Generated by Django 5.0 on 2025-04-25 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orders_order_date_alter_orders_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Card (Debit/Credit)'), ('upi', 'UPI'), ('cod', 'Cash on Delivery')], max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orders')),
            ],
        ),
    ]
